import ellipse from '../../assets/Ellipse 1.png' 
import ellipse1 from '../../assets/Ellipse 1 (1).png'
import ellipse2 from '../../assets/Ellipse 1 (2).png'

export const Data = [{
    image: ellipse , 
    user: 'Jennydev', 
    title: 'Storing RegEX inside of JSON[Duplicate]',
     tweet: 'I get the following error: test is no defined, whenever I run the codebelow:import WindMouse from ../src/index;test...', 
     likes: '30', 
     comments: '17',
      date: '5 Days Ago',
},
{
    image: ellipse1, 
    user: 'mae.dev', 
    title: 'Html editor with preview[closed]',
     tweet: 'Any idea or sample project about data structure, binding of a html editor like wix? Having boxes, by click shows context menu, by changing data mo...', 
     likes: '20', 
     comments: '3',
      date: '2 months Ago',
},
{
    image: ellipse2 , 
    user: 'Anonymous', 
    title: 'Overriding Html from a third party components',
     tweet: 'Aye Im Dave. does any one know how to override the HTML text of third-party software, I use an appointment-scheduling...', 
     likes: '10', 
     comments: '20',
      date: '5 days Ago',
},
{
    image: ellipse2 , 
    user: 'Unknown',
    title: 'Firebase cloud functions return api token',
     tweet: 'I have an axios instance that I use to fetch data: const getQualtrics = axios.create({ baseURL: https://xx1.qualtrics.com/API/v3/, headers:...,' ,
     likes: '30', 
     comments: '17',
      date: '9 months Ago',
},
{
    image: ellipse2 , 
    user: 'Unknow', 
    title: 'Storing RegEX inside of JSON[Duplicate]',
     tweet: 'I am trying to create a way to validate specific data types. But I keep getti...click shows context menu, by changing data mo...', 
     likes: '30', 
     comments: '17',
      date: '6 months Ago',
},
{
    image: ellipse2 , 
    user: 'useranon', 
    title: 'Test is not defined[duplicate]',
     tweet: 'I get the following error: test is not defined, whenever I run the code below: import WindMouse from "../src/index"; test...', 
     likes: '10', 
     comments: '15',
      date: '5 years Ago',
},
{
    image: ellipse2 , 
    user: 'David ', 
    title: 'Dependency interjector error when i deploy it',
     tweet: 'I am trying to create a way to validate specific data types. But I keep getticlick shows context menu, by changing data mo...', 
     likes: '30', 
     comments: '17',
      date: '5 years Ago',
},
{
    image: ellipse2 , 
    user: 'lord repo ', 
    title: 'How to use jet-dom as a stand alone in a webpage',
     tweet: 'I want to use/run jest-dom matchers separately/standalone (not in a test, but in a webpage) like this: import matchers from...', 
     likes: '30', 
     comments: '17',
      date: '5 years Ago',
},
{
    image: ellipse2 , 
    user: 'Noble', 
    title: 'Set method when instance iscreated',
     tweet: 'Is there any way to execute the set method when an instance is created?. I have this piece of code: class CoffeeMachine { _power...', 
     likes: '30', 
     comments: '17',
      date: '11 months ago',
},
{
    image: ellipse2 , 
    user: 'dipo ', 
    title: 'Compress texts into letters and numbers',
     tweet: 'I want to write a tinyurl clone, and take text like: https://myfunwebsite.com/coolthing and shorten that string to something like..', 
     likes: '10', 
     comments: '17',
      date: '6 months ago',
},
{
    image: ellipse2 , 
    user: 'James', 
    title: 'Storing RegEX inside of JSON[Duplicate]',
     tweet: 'I am trying to create a way to validate specific data types. But I keep getticlick shows context menu, by changing data mo', 
     likes: '30', 
     comments: '17',
      date: '1 year Ago',
},
{
    image: ellipse2 , 
    user: 'giftedhands', 
    title: 'CSC calc mixed use of height and width',
     tweet: "I have a div element (with a background image) that I want to occupy the smaller of 40% of the parent element's width... ", 
     likes: '20', 
     comments: '10',
      date: '1 month Ago',
},
]