const users = [
	{
		img: '../assets/userPageAssets/Ellipse0.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse1.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse2.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse3.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse4.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse5.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse6.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse7.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse8.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse16.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse11.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse10.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse12.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse1.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse5.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse11.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse15.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse14.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse10.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse17.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse7.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse14.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse1.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../assets/userPageAssets/Ellipse3.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},

	{
		img: '../assets/userPageAssets/Ellipse21.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
	{
		img: '../asssts/userPageAssets/Ellipse19.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},

	{
		img: '../assets/userPageAssets/Ellipse20.png',
		userName: 'Ada Stevens',
		userStack: 'Senior Product Designer',
		followers: '1570',
		userFavoriteLanguage: 'sql, oracle, windows-options',
	},
];
export default users;
